### PR TITLE
Removed try catch to allow Craft Mailer to catch exceptions

### PR DESCRIPTION
**Pull request by noahjahn**
This PR was raised to help those trying to diagnose problems with their SES configuration.

## Enhancements
* Removed try catch to allow Craft Mailer to catch exceptions

### CODE REVIEW

**Comment by bencroker** [comment]
Thanks for the PR. Since the Mailer class catches exceptions, I wonder if it would be better to remove the try/catch statement completely. Would you mind testing this and see if the results are the same?

```php
    public function send(Swift_Mime_SimpleMessage $message, &$failedRecipients = null): int
    {
        $data = $this->_formatMessage($message);

        $this->_client->sendRawEmail($data);

        return count($message->getTo());
    }
```

**Comment by noahjahn** [comment]
Aha, great catch. For some reason I thought this function was overriding the Craft Mailer send method..

The results are the same with your suggestion -- thanks!

**Comment by bencroker** [comment]
Merged, thanks!

**Comment by bencroker** [comment]
Released in 1.3.4.

**Pull request merged**
